### ISSUE TITLE
Getting error when running code

### ISSUE THREAD

**Issue by sathi081289** [lululeon/sourcerer#2]
Invoking R script... at: E:\NewRscript\sourcerer\src\sourcerer-core\wordcloud.R
Finished with error: { Error: spawn wordcloud.R ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by lululeon** [comment]
closing now.
